### ISSUE TITLE
Is the Re-ranking operation in eq.(7) used in the training stage?

### ISSUE THREAD

**Issue by cty8998** [leolee99/PAU#3]
Is the Re-ranking operation in eq.(7) used in the training stage? If not, how to train the learnable parameters β1 and β2 in eq.(7)?

Besides, the video_sentence_logits and sentence_frame_logits are both used in the training and testing stage, is it right?

**Comment by leolee99** [comment]
1) Thank you for your interest in our work. Re-ranking operation in eq. (7) is not used during the training stage. After training, $\beta_1$ and $\beta_2$ can be individually learned using simple optimization algorithms, such as Nelder-Mead and BFGS . We have integrated and updated the beta learning code into the repository. You can refer it at "[main_pau.py: L432-L449](https://github.com/leolee99/PAU/blob/233b7797f89f043bcc806868c48153e8eb0e8a9d/main_pau.py#L432-L449.)"

2) Yes, both video_sentence_logits and sentence_frame_logits are used during the training and testing stages.
