### ISSUE TITLE
about MSCOCO

### ISSUE THREAD

**Issue by xiaoxiaoxiaofufu** [leolee99/PAU#5]
Nice work!For the past few days, I have read your paper and codes, but I still quite confused about how to apply your method(or uncertainy) to MSCOCO which is image-based instead of vedio, would you be kind to share the details or provide with the code in MSCOCO.My email address is kaiq663@foxmail.com

**Comment by leolee99** [comment]
Hi, thanks for your interest and patient waiting. The implementation of Image-text retrieval has been updated. You can find it in [PAU/Image-Text-Retrieval](https://github.com/leolee99/PAU/tree/main/Image-Text-Retrieval).

**Comment by xiaoxiaoxiaofufu** [comment]
> Hi, thanks for your interest and patient waiting. The implementation of Image-text retrieval has been updated. You can find it in [PAU/Image-Text-Retrieval](https://github.com/leolee99/PAU/tree/main/Image-Text-Retrieval).

Thank you sooooooo much !

**Comment by leolee99** [comment]
😄
