### ISSUE TITLE
VSE infinity reproduction

### ISSUE THREAD

**Issue by AOPALUNPA** [leolee99/PAU#6]

**Comment by leolee99** [comment]
Thanks for your interests to our work. The experimental results of VSE infinity come from the paper of ["Improved Probabilistic Image-Text Representations"](https://arxiv.org/abs/2305.18171). The full results can be found in [URL](https://docs.google.com/spreadsheets/d/1EMbp03uD7X5puN80zV2wr43Z2FWC4wQ9bo8HXcyU27k/edit?usp=sharing).

**Comment by AOPALUNPA** [comment]
> Thanks for your interests to our work. The experimental results of VSE infinity come from the paper of ["Improved Probabilistic Image-Text Representations"](https://arxiv.org/abs/2305.18171). The full results can be found in [URL](https://docs.google.com/spreadsheets/d/1EMbp03uD7X5puN80zV2wr43Z2FWC4wQ9bo8HXcyU27k/edit?usp=sharing).

Thanks for your reply, got it.
